routes/web.php
<?php

use App\Http\Controllers\Back\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/store', function () {
    return view('front.store');
});
Route::resource('/product',ProductController::class);

resources/views/front/footer.blade.php
<footer id="footer">
    <h2>Resturant Website &copy; all rights reserved</h2>
</footer>

resources/views/front/header.blade.php
<nav class="navbar">
    <div class="navbar-container container">
        <input type="checkbox" name="" id="">
        <div class="hamburger-lines">
            <span class="line line1"></span>
            <span class="line line2"></span>
            <span class="line line3"></span>
        </div>
        <ul class="menu-items">
            <li><a href="#showcase">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#food">Category</a></li>
            <li><a href="#testimonial">Testimonial</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
        <h1 class="logo">FW</h1>
    </div>
</nav>

<div class="product-content">
    <div class="product">

        <li><a href="/store">Add products</a></li>
        
    </div>
</div>
    

resources/views/front/main.blade.php
@extends('front.master')
@section('content')
<section class="showcase-area" id="showcase">
    <div class="showcase-container">
        <h1 class="main-title">Eat Right Food</h1>
        <p>Eat healty food to be healty and fit</p>
        <a href="#food-menu" class="btn btn-primary">Menu</a>
    </div>
</section>



<section id="about">
    <div class="about-wrapper container">
        <div class="about-text">
            <p class="small">About Us</p>
            <h2>We have been making food for last 20 years for you</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum fugit voluptates neque illum voluptas doloribus, iste fuga laboriosam assumenda cupiditate quo quod repudiandae. Dolorem itaque vero distinctio quam harum eveniet!</p>
        </div>
        <div class="about-img">
            <img src="./images/about-photo.jpg" alt="About Us">
        </div>
    </div>
</section>

<section id="food">
    <h2>Please choose </h2>
    <div class="food-container container">
        <div class="food-type fruit">
            <div class="img-container">
                <img src="./images/vegPizza.webp" alt="">
                {{-- <img src="{{ asset('food1.jpg') }}" alt=""> --}}

                <div class="img-content">
                    <h3>Veg</h3>
                    <a href="https://en.wikipedia.org/wiki/Fruit" class="btn btn-primary" target="_blank">Click me</a>

                </div>
            </div>
        </div>
        <div class="food-type vegetable">
            <div class="img-container">
            <img src="./images/nonVegPizza.jpeg" alt="">
            <div class="img-content">
                <h3>Non-veg</h3>
                <a href="https://en.wikipedia.org/wiki/Vegetable" class="btn btn-primary" target="_blank">Click me</a>
            </div>
            </div>
        </div>
        {{-- <div class="food-type grain">
            <div class="img-container">

            <img src="./images/food3.jpg" alt="">
            <div class="img-content">
                <h3>Grain</h3>
                <a href="https://en.wikipedia.org/wiki/Grain" class="btn btn-primary" target="_blank">Learn More</a>

            </div>
            </div>
        </div> --}}
        </div>
    </div>
</section>

<section id="food-menu">
    <h2 class="food-menu-heading">
        Food Menu
    </h2>
    <div class="food-menu-container">
        <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu1.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>
        <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu2.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 2</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>   <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu3.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 3</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>   <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu4.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 4</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>   <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu5.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 5</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>   <div class="food-menu-item">
            <div class="food-image">
                <img src="./images/food-menu6.jpg" alt="">
            </div>
            <div class="food-description">
                <h2 class="food-title">Food Menu Item 6</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, optio. Rem, iste, sequi expedita omnis autem numquam culpa placeat aspernatur sit iure quos temporibus magnam exercitationem iusto ex minus ut!</p>
                <p class="food-price">price: &#36; 10.99</p>
            </div>
        </div>

    </div>
</section>

<section id="testimonial">
    <h2 class="testimonial-title">What Our Customer Says</h2>
    <div class="testimonial-container container">
        <div class="testimonial-box">
            <div class="star-rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>


            </div>
            <p class="testimonial-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita dolorum vitae voluptatem aliquid et autem praesentium qui iure necessitatibus ratione ut cum in, sunt at iusto accusantium voluptates ullam consectetur.</p>
            <div class="customer-detail">
                <div class="customer-photo">
                    <img src="./images/male1.jpeg" alt="">
                </div>
                <div class="customer-name">Jhon Doe</div>
            </div>
        </div>
        <div class="testimonial-box">
            <div class="star-rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span> 

            </div>
            <p class="testimonial-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita dolorum vitae voluptatem aliquid et autem praesentium qui iure necessitatibus ratione ut cum in, sunt at iusto accusantium voluptates ullam consectetur.</p>
            <div class="customer-detail">
                <div class="customer-photo">
                    <img src="./images/male2.JPG" alt="">
                </div>
                <div class="customer-name">jay Doe</div>
            </div>
        </div><div class="testimonial-box">
            <div class="star-rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>

            </div>
            <p class="testimonial-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita dolorum vitae voluptatem aliquid et autem praesentium qui iure necessitatibus ratione ut cum in, sunt at iusto accusantium voluptates ullam consectetur.</p>
            <div class="customer-detail">
                <div class="customer-photo">
                    <img src="./images/male3.png" alt="">
                </div>
                <div class="customer-name">Gunny Doe</div>
            </div>
        </div>
    </div>
</section>

<section id="contact">
    <div class="contact-container container">
        <div class="contact-image">
            <img src="./images/restraunt-image.jpg" alt="">
        </div>
        <div class="form-container">
            <h2>Contact Us</h2>
            <input type="text" name="" id="" placeholder="Name">
            <input type="email" name="" id="" placeholder="E-mail">
            <textarea name="" id="" cols="30" rows="10" placeholder="Type Your Message Here"></textarea>
            <a href="#" class="btn btn-primary">Submit</a>
        </div>
    </div>
</section>
    
@endsection

resources/views/front/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diwash Pizza Shop</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{{ asset('js/script.js') }}"></script>





</head>
<body>
    @include('front.header')
    @yield('content')
    @include('front.footer')

    
</body>

resources/views/front/store.blade.php
@extends('front.master')
@section('content')
    <!------ Include the above in your HEAD tag ---------->
    {{-- @if ($errors->any())
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
    @endif --}}
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    <div> 
        <form class="form-horizontal" action="{{ route('product.store') }}" method='POST'>
            @csrf
            <fieldset>
                <!-- Form Name -->
                <legend>PRODUCTS</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="name">PRODUCT NAME</label>
                    <div class="col-md-4">
                        <input id="product_name" name="name" placeholder="PRODUCT NAME" class="form-control input-md"
                            type="text">

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="name">PRODUCT TYPE</label>
                    <div class="col-md-4">
                        <input id="type" name="type" placeholder="PRODUCT TYPE" class="form-control input-md"
                            type="text">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="description">PRODUCT PRICE</label>
                    <div class="col-md-4">
                        <input id="price" name="price" placeholder="price" class="form-control input-md"
                            type="text">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="total_quantity">AVAILABLE QUANTITY</label>
                    <div class="col-md-4">
                        <input id="total_quantity" name="total_quantity" placeholder="AVAILABLE QUANTITY"
                            class="form-control input-md" type="text">

                    </div>
                </div>
             

                <!-- Textarea -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="description">PRODUCT DESCRIPTION</label>
                    <div class="col-md-4">
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </div>



                <!-- Button -->
                <div class="form-group">
                    <div class="col-md-4">
                        <button id="add" name="add" class="btn btn-primary">Add Product</button>
                       
                    </div>

                </div>

            </fieldset>
        </form>


    </div>
@endsection